version: '3'

services:
  my_nginx:
    container_name: my_nginx
    image: nginx
    ports:
      - "81:80"
    volumes:
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./php/www:/var/www/public_html
    depends_on:
      - api
      - my_db
  api:
    container_name: api
    build: ./php
    volumes:
      - ./php/www:/var/www/public_html
    depends_on:
      - my_db
  my_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: tartar2002
      MYSQL_DATABASE: loan_db
    volumes:
      - ./db:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - '8889:8080'
    depends_on:
      - my_db

